# delete

- name: Rocket.Chat notification with credentials
  uses: jadolg/rocketchat-notification-action@v1.0.0
  
# https://github.com/marketplace/actions/rocket-chat-notification-with-credentials
on: [push]

jobs:
  rocketchat_job:
    runs-on: ubuntu-latest
    name: Push notification to rocket.chat
    steps:
    - name: Push notification to rocket.chat if the job failed
      id: error-notification
      if: ${{ failure() }}
      uses: jadolg/rocketchat-notification-action@v1.0.1
      with:
        server: ${{ secrets.ROCKETCHAT_SERVER }}
        message: Wooops! Looks like something went wrong!
        user: ${{ secrets.ROCKETCHAT_USER }}
        password: ${{ secrets.ROCKETCHAT_PASSWORD }}
        channel: testgithub

name: PR_alert
on:
  pull_request:
    types: [opened, reopened]
    branches: [ master ]

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
    - name: Push notification when a Pull Request is created
      uses: jadolg/rocketchat-notification-action@v1.0.1
      with:
        message: Woop! Woop! A new Pull Request has being created at ${{ github.event.pull_request.html_url }}
        user: ${{ secrets.ROCKETCHAT_USER }}
        password: ${{ secrets.ROCKETCHAT_PASSWORD }}
        channel: testgithub
        code: false
