on: [push]

jobs:
  rocketchat_job:
    runs-on: ubuntu-latest
    name: Push notification to rocket.chat
    steps:
    - name: Push notification to rocket.chat if the job failed
      id: error-notification
      if: ${{ failure() }}
      uses: jadolg/rocketchat-notification-action@v1.0.1
      with:
        server: ${{ secrets.ROCKETCHAT_SERVER }}
        message: Wooops! Looks like something went wrong!
        user: ${{ secrets.ROCKETCHAT_USER }}
        password: ${{ secrets.ROCKETCHAT_PASSWORD }}
        channel: testgithub


